/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_COMMON_COMMON_PB_H_INCLUDED
#define PB_COMMON_COMMON_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* 返回结果 */
typedef enum _Common_RetType {
    Common_RetType_RetType_Succeed = 0, /* 成功 */
    Common_RetType_RetType_Failed = -1, /* 失败 */
    Common_RetType_RetType_TimeOut = -100, /* 超时 */
    Common_RetType_RetType_DisConnect = -200, /* 连接断开 */
    Common_RetType_RetType_Unknown = -400, /* 未知结果 */
    Common_RetType_RetType_Invalid = -500 /* 包内容非法 */
} Common_RetType;

/* 包加密算法 */
typedef enum _Common_PacketEncAlgo {
    Common_PacketEncAlgo_PacketEncAlgo_FTAES_ECB = 0, /* 富途修改过的AES的ECB加密模式 */
    Common_PacketEncAlgo_PacketEncAlgo_None = -1, /* 不加密 */
    Common_PacketEncAlgo_PacketEncAlgo_AES_ECB = 1, /* 标准的AES的ECB加密模式 */
    Common_PacketEncAlgo_PacketEncAlgo_AES_CBC = 2 /* 标准的AES的CBC加密模式 */
} Common_PacketEncAlgo;

/* 协议格式，请求协议在请求头中指定，推送协议在Init时指定 */
typedef enum _Common_ProtoFmt {
    Common_ProtoFmt_ProtoFmt_Protobuf = 0, /* Google Protobuf格式 */
    Common_ProtoFmt_ProtoFmt_Json = 1 /* Json格式 */
} Common_ProtoFmt;

/* 用户注册归属地 */
typedef enum _Common_UserAttribution {
    Common_UserAttribution_UserAttribution_Unknown = 0, /*  */
    Common_UserAttribution_UserAttribution_NN = 1, /* 大陆 */
    Common_UserAttribution_UserAttribution_MM = 2, /* MooMoo */
    Common_UserAttribution_UserAttribution_SG = 3, /* 新加坡 */
    Common_UserAttribution_UserAttribution_AU = 4, /* 澳洲 */
    Common_UserAttribution_UserAttribution_JP = 5, /* 日本 */
    Common_UserAttribution_UserAttribution_HK = 6 /* 香港 */
} Common_UserAttribution;

typedef enum _Common_ProgramStatusType {
    Common_ProgramStatusType_ProgramStatusType_None = 0,
    Common_ProgramStatusType_ProgramStatusType_Loaded = 1, /* 已完成类似加载配置,启动服务器等操作,服务器启动之前的状态无需返回 */
    Common_ProgramStatusType_ProgramStatusType_Loging = 2, /* 登录中 */
    Common_ProgramStatusType_ProgramStatusType_NeedPicVerifyCode = 3, /* 需要图形验证码 */
    Common_ProgramStatusType_ProgramStatusType_NeedPhoneVerifyCode = 4, /* 需要手机验证码 */
    Common_ProgramStatusType_ProgramStatusType_LoginFailed = 5, /* 登录失败,详细原因在描述返回 */
    Common_ProgramStatusType_ProgramStatusType_ForceUpdate = 6, /* 客户端版本过低 */
    Common_ProgramStatusType_ProgramStatusType_NessaryDataPreparing = 7, /* 正在拉取类似免责声明等一些必要信息 */
    Common_ProgramStatusType_ProgramStatusType_NessaryDataMissing = 8, /* 缺少必要信息 */
    Common_ProgramStatusType_ProgramStatusType_UnAgreeDisclaimer = 9, /* 未同意免责声明 */
    Common_ProgramStatusType_ProgramStatusType_Ready = 10, /* 可以接收业务协议收发,正常可用状态 */
    /* OpenD登录后被强制退出登录，会导致连接全部断开,需要重连后才能得到以下该状态（并且需要在ui模式下） */
    Common_ProgramStatusType_ProgramStatusType_ForceLogout = 11, /* 被强制退出登录,例如修改了登录密码,中途打开设备锁等,详细原因在描述返回 */
    Common_ProgramStatusType_ProgramStatusType_DisclaimerPullFailed = 12 /* 拉取免责声明标志失败 */
} Common_ProgramStatusType;

/* Struct definitions */
/* 包的唯一标识，用于回放攻击的识别和保护 */
typedef struct _Common_PacketID {
    uint64_t connID; /* 当前TCP连接的连接ID，一条连接的唯一标识，InitConnect协议会返回 */
    uint32_t serialNo; /* 自增序列号 */
} Common_PacketID;

typedef struct _Common_ProgramStatus {
    Common_ProgramStatusType type; /* 当前状态 */
    pb_callback_t strExtDesc; /* 额外描述 */
} Common_ProgramStatus;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _Common_RetType_MIN Common_RetType_RetType_Invalid
#define _Common_RetType_MAX Common_RetType_RetType_Succeed
#define _Common_RetType_ARRAYSIZE ((Common_RetType)(Common_RetType_RetType_Succeed+1))

#define _Common_PacketEncAlgo_MIN Common_PacketEncAlgo_PacketEncAlgo_None
#define _Common_PacketEncAlgo_MAX Common_PacketEncAlgo_PacketEncAlgo_AES_CBC
#define _Common_PacketEncAlgo_ARRAYSIZE ((Common_PacketEncAlgo)(Common_PacketEncAlgo_PacketEncAlgo_AES_CBC+1))

#define _Common_ProtoFmt_MIN Common_ProtoFmt_ProtoFmt_Protobuf
#define _Common_ProtoFmt_MAX Common_ProtoFmt_ProtoFmt_Json
#define _Common_ProtoFmt_ARRAYSIZE ((Common_ProtoFmt)(Common_ProtoFmt_ProtoFmt_Json+1))

#define _Common_UserAttribution_MIN Common_UserAttribution_UserAttribution_Unknown
#define _Common_UserAttribution_MAX Common_UserAttribution_UserAttribution_HK
#define _Common_UserAttribution_ARRAYSIZE ((Common_UserAttribution)(Common_UserAttribution_UserAttribution_HK+1))

#define _Common_ProgramStatusType_MIN Common_ProgramStatusType_ProgramStatusType_None
#define _Common_ProgramStatusType_MAX Common_ProgramStatusType_ProgramStatusType_DisclaimerPullFailed
#define _Common_ProgramStatusType_ARRAYSIZE ((Common_ProgramStatusType)(Common_ProgramStatusType_ProgramStatusType_DisclaimerPullFailed+1))


#define Common_ProgramStatus_type_ENUMTYPE Common_ProgramStatusType


/* Initializer values for message structs */
#define Common_PacketID_init_default             {0, 0}
#define Common_ProgramStatus_init_default        {_Common_ProgramStatusType_MIN, {{NULL}, NULL}}
#define Common_PacketID_init_zero                {0, 0}
#define Common_ProgramStatus_init_zero           {_Common_ProgramStatusType_MIN, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define Common_PacketID_connID_tag               1
#define Common_PacketID_serialNo_tag             2
#define Common_ProgramStatus_type_tag            1
#define Common_ProgramStatus_strExtDesc_tag      2

/* Struct field encoding specification for nanopb */
#define Common_PacketID_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   connID,            1) \
X(a, STATIC,   REQUIRED, UINT32,   serialNo,          2)
#define Common_PacketID_CALLBACK NULL
#define Common_PacketID_DEFAULT NULL

#define Common_ProgramStatus_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UENUM,    type,              1) \
X(a, CALLBACK, OPTIONAL, STRING,   strExtDesc,        2)
#define Common_ProgramStatus_CALLBACK pb_default_field_callback
#define Common_ProgramStatus_DEFAULT NULL

extern const pb_msgdesc_t Common_PacketID_msg;
extern const pb_msgdesc_t Common_ProgramStatus_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Common_PacketID_fields &Common_PacketID_msg
#define Common_ProgramStatus_fields &Common_ProgramStatus_msg

/* Maximum encoded size of messages (where known) */
/* Common_ProgramStatus_size depends on runtime parameters */
#define COMMON_COMMON_PB_H_MAX_SIZE              Common_PacketID_size
#define Common_PacketID_size                     17

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
