/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "InitConnect.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(InitConnect_C2S, InitConnect_C2S, AUTO)


PB_BIND(InitConnect_S2C, InitConnect_S2C, AUTO)


PB_BIND(InitConnect_Request, InitConnect_Request, AUTO)


PB_BIND(InitConnect_Response, InitConnect_Response, AUTO)



