/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_KEEPALIVE_KEEPALIVE_PB_H_INCLUDED
#define PB_KEEPALIVE_KEEPALIVE_PB_H_INCLUDED
#include <pb.h>
#include "Common.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _KeepAlive_C2S {
    int64_t time; /* 客户端发包时的格林威治时间戳，单位秒 */
} KeepAlive_C2S;

typedef struct _KeepAlive_S2C {
    int64_t time; /* 服务器回包时的格林威治时间戳，单位秒 */
} KeepAlive_S2C;

typedef struct _KeepAlive_Request {
    KeepAlive_C2S c2s;
} KeepAlive_Request;

typedef struct _KeepAlive_Response {
    int32_t retType; /* RetType,返回结果 */
    pb_callback_t retMsg;
    bool has_errCode;
    int32_t errCode;
    bool has_s2c;
    KeepAlive_S2C s2c;
} KeepAlive_Response;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define KeepAlive_C2S_init_default               {0}
#define KeepAlive_S2C_init_default               {0}
#define KeepAlive_Request_init_default           {KeepAlive_C2S_init_default}
#define KeepAlive_Response_init_default          {-400, {{NULL}, NULL}, false, 0, false, KeepAlive_S2C_init_default}
#define KeepAlive_C2S_init_zero                  {0}
#define KeepAlive_S2C_init_zero                  {0}
#define KeepAlive_Request_init_zero              {KeepAlive_C2S_init_zero}
#define KeepAlive_Response_init_zero             {0, {{NULL}, NULL}, false, 0, false, KeepAlive_S2C_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define KeepAlive_C2S_time_tag                   1
#define KeepAlive_S2C_time_tag                   1
#define KeepAlive_Request_c2s_tag                1
#define KeepAlive_Response_retType_tag           1
#define KeepAlive_Response_retMsg_tag            2
#define KeepAlive_Response_errCode_tag           3
#define KeepAlive_Response_s2c_tag               4

/* Struct field encoding specification for nanopb */
#define KeepAlive_C2S_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT64,    time,              1)
#define KeepAlive_C2S_CALLBACK NULL
#define KeepAlive_C2S_DEFAULT NULL

#define KeepAlive_S2C_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT64,    time,              1)
#define KeepAlive_S2C_CALLBACK NULL
#define KeepAlive_S2C_DEFAULT NULL

#define KeepAlive_Request_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  c2s,               1)
#define KeepAlive_Request_CALLBACK NULL
#define KeepAlive_Request_DEFAULT NULL
#define KeepAlive_Request_c2s_MSGTYPE KeepAlive_C2S

#define KeepAlive_Response_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    retType,           1) \
X(a, CALLBACK, OPTIONAL, STRING,   retMsg,            2) \
X(a, STATIC,   OPTIONAL, INT32,    errCode,           3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  s2c,               4)
#define KeepAlive_Response_CALLBACK pb_default_field_callback
#define KeepAlive_Response_DEFAULT (const pb_byte_t*)"\x08\xf0\xfc\xff\xff\xff\xff\xff\xff\xff\x01\x00"
#define KeepAlive_Response_s2c_MSGTYPE KeepAlive_S2C

extern const pb_msgdesc_t KeepAlive_C2S_msg;
extern const pb_msgdesc_t KeepAlive_S2C_msg;
extern const pb_msgdesc_t KeepAlive_Request_msg;
extern const pb_msgdesc_t KeepAlive_Response_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define KeepAlive_C2S_fields &KeepAlive_C2S_msg
#define KeepAlive_S2C_fields &KeepAlive_S2C_msg
#define KeepAlive_Request_fields &KeepAlive_Request_msg
#define KeepAlive_Response_fields &KeepAlive_Response_msg

/* Maximum encoded size of messages (where known) */
/* KeepAlive_Response_size depends on runtime parameters */
#define KEEPALIVE_KEEPALIVE_PB_H_MAX_SIZE        KeepAlive_Request_size
#define KeepAlive_C2S_size                       11
#define KeepAlive_Request_size                   13
#define KeepAlive_S2C_size                       11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
