/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "Common.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Common_PacketID, Common_PacketID, AUTO)


PB_BIND(Common_ProgramStatus, Common_ProgramStatus, AUTO)













