/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "KeepAlive.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(KeepAlive_C2S, KeepAlive_C2S, AUTO)


PB_BIND(KeepAlive_S2C, KeepAlive_S2C, AUTO)


PB_BIND(KeepAlive_Request, KeepAlive_Request, AUTO)


PB_BIND(KeepAlive_Response, KeepAlive_Response, AUTO)



